class FontList {
  static const fonts = [
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Poppins',
    'Nunito',
    'Raleway',
    'Inter',
    'Work Sans',
    'Rubik',
    'Quicksand',
    'Heebo',
    'Merriweather',
    'Playfair Display',
    'Lora',
    'Bitter',
    'Cormorant Garamond',
    'Oswald',
    'Pacifico',
    'Dancing Script',
    'Abril Fatface',
    'Bebas Neue',
    'Great Vibes',
    'Lobster',
    'Shadows Into Light',
    'Roboto Mono',
    'Inconsolata',
    'Source Code Pro',
    'Space Mono',
    'Fira Code',
    'Exo 2',
    'Titillium Web',
    'Oxygen',
    'Josefin Sans',
    'Kanit',
    'Baloo 2',
    'Varela Round',
    'M PLUS Rounded 1c',
    'Fredoka',

    'Urbanist',
    'Manrope',
    'Barlow',
    'Plus Jakarta Sans',
  ];
}
